### ISSUE TITLE
First item with half-visible items

### ISSUE THREAD

**Issue by fsshopmacher** [SHOPMACHER/sm-slider#1]
Hi,

if I use `"visibleSlides": 1.4,` the prev and next item should be visible before and after the active item. At the moment only the last item is visible. Any ideas how to realize this?

Thank you
Franziska

**Comment by rherwig** [comment]
I'm gonna take a look at this now. ;-)

**Comment by rherwig** [comment]
The feature has been implemented in [v1.2.0](https://github.com/SHOPMACHER/sm-slider/releases/tag/v1.2.0) of sm-slider.

You can now use the `offsetLeft` option in your general and breakpoint config. This is a number ranging from 0 to 1, which controls the percentage of the slide that is visible before the currently active one.

For best results, use a non-decimal value for `visibleSlides`, since decimals might look a little confusing and lead to uneven results.

The documentation has been extended as well.

`npm i -S sm-slider@1.2.0` to get this release.
